In [1]:
import numpy as np

In [4]:
%%time    # should be on first line 
[i for i in range(1,10)]

CPU times: total: 0 ns
Wall time: 1e+03 µs


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
l1=[3,5,6,2]
[i+5 for i in l1] 

[8, 10, 11, 7]

In [7]:
l2=np.array([1,2,3,4,5])
print(l2,type(l2))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
%%time
l1=np.arange(1,10000000)
l1 + 5

CPU times: total: 31.2 ms
Wall time: 40.7 ms


array([       6,        7,        8, ..., 10000002, 10000003, 10000004])

In [9]:
np.__version__

'1.23.5'

In [14]:
l1 = [1,2,3],[4,5,6],[7,8,9]

for rid,v in enumerate(l1):
    for cid,_ in enumerate(v):
        l1[rid][cid] += 5

In [15]:
l1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
l1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
#scalar data
a= np.array(5)

print(a)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)

5
<class 'numpy.ndarray'>
()
0
1


In [22]:
#vector data
a= np.array([1,2,3])

print(a)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3


In [23]:
#MATRICS
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
2
9


In [25]:
a = np.arange(2*4*6).reshape(2,4,6)

print(a)
print("type",type(a))
print("shape",a.shape)
print("dimension",a.ndim)
print("size",a.size)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]]]
type <class 'numpy.ndarray'>
shape (2, 4, 6)
dimension 3
size 48


In [26]:
a = 5
b = a
c = a
d = a 

print(id(a))
print(id(b))
print(id(c))
print(id(d))

2201474826608
2201474826608
2201474826608
2201474826608


In [ ]:
a = np.array([1,2,3])
b =a.copy()

print(a,b)
print(id(a),id(b))

a(0) = 7
print()
a = np.arange(1,11

In [28]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a = np.random.random((2,3))
a

array([[0.63313021, 0.7947099 , 0.3314606 ],
       [0.52797036, 0.03159453, 0.01817837]])

In [34]:
a = np.random.randint(1,100,5)
a

array([12, 53, 71, 55, 12])

In [37]:
a = np.random.choice(["A","B",2,"7","C"],3,False)
a

array(['2', '7', 'C'], dtype='<U11')

In [36]:
a = np.random.choice(["A","B",2,"7","C"],100)
a

array(['C', 'A', '2', 'B', 'C', '2', '2', 'A', 'B', '2', 'C', 'C', 'C',
       '7', '2', 'A', '7', '2', '2', 'A', 'C', '7', '2', '2', 'B', 'B',
       'C', 'C', 'C', 'A', '2', '2', 'A', '7', '7', 'C', 'A', 'C', '2',
       '7', '7', 'B', 'B', 'C', 'C', 'C', '7', '2', 'A', '2', '7', '7',
       'A', 'A', 'A', '7', 'A', 'C', 'C', '7', '7', 'A', '7', 'C', 'C',
       'A', 'C', 'B', 'A', 'A', '2', 'A', '2', 'C', '2', 'C', '2', 'B',
       'A', 'B', 'A', 'B', '2', 'B', '2', '2', '2', '2', 'B', 'C', 'C',
       '2', 'B', 'A', 'C', 'B', '7', 'A', 'B', 'A'], dtype='<U11')

In [39]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
a = np.arange(5*25*3*10*10).reshape((5,25,3,10,10))
a

array([[[[[    0,     1,     2, ...,     7,     8,     9],
          [   10,    11,    12, ...,    17,    18,    19],
          [   20,    21,    22, ...,    27,    28,    29],
          ...,
          [   70,    71,    72, ...,    77,    78,    79],
          [   80,    81,    82, ...,    87,    88,    89],
          [   90,    91,    92, ...,    97,    98,    99]],

         [[  100,   101,   102, ...,   107,   108,   109],
          [  110,   111,   112, ...,   117,   118,   119],
          [  120,   121,   122, ...,   127,   128,   129],
          ...,
          [  170,   171,   172, ...,   177,   178,   179],
          [  180,   181,   182, ...,   187,   188,   189],
          [  190,   191,   192, ...,   197,   198,   199]],

         [[  200,   201,   202, ...,   207,   208,   209],
          [  210,   211,   212, ...,   217,   218,   219],
          [  220,   221,   222, ...,   227,   228,   229],
          ...,
          [  270,   271,   272, ...,   277,   278,   279],
       