In [1]:
import pandas as pd
import numpy as np

In [3]:
ar1 = np.array([100,200,300,400,500,600])
print(ar1[2])
print(ar1[-3])

300
400


In [4]:
ar1 = np.array([100,200,300,400,500,600])

print(ar1[1:4])
print(ar1[1:5:1])
print(ar1[1:5:2])


[200 300 400]
[200 300 400 500]
[200 400]


In [11]:
l1=["a","b","c","d","e"]
display(type(11))
display(11)


ll1= pd.Series(l1)
display(type(ll1))
display(ll1)

int

11

pandas.core.series.Series

0    a
1    b
2    c
3    d
4    e
dtype: object

In [14]:
data = np.arange(10*5).reshape((10,5))
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [16]:
df = ([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])


df = pd.DataFrame(df)
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

In [2]:
l1 = ['a','b','c','d','e']
display(type(l1))
display(l1)


ll1 = pd.Series(l1)
display(type(ll1))
display(ll1)

list

['a', 'b', 'c', 'd', 'e']

pandas.core.series.Series

0    a
1    b
2    c
3    d
4    e
dtype: object

In [3]:
l1 =  [1,2,3]
pd.Series(l1, dtype=np.float64)

0    1.0
1    2.0
2    3.0
dtype: float64

In [4]:
data = np.arange(10*5).reshape((10,5))
df1 = pd.DataFrame(data, 
                  columns=['a','b','c','d','e'])
df1

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

In [9]:
sample= 10000

df = pd.DataFrame({
    "roll_number": np.arange(1,sample+1),
    "student name": np.random.choice(["Ali","Hamza","Junaid","Asif","Raza"], sample),
    "father name": np.random.choice(["Ebad","Hashim","Konain","Yasir","Iqbal"], sample),
    "DOB": np.random.choice(pd.date_range("1960-01-01", "2015-12-31",freq="D").values, sample),
    "s1": np.random.randint(1,100, sample),
    "s2": np.random.randint(1,100, sample),
    "s3": np.random.randint(1,100, sample),
    "s4": np.random.randint(1,100, sample),
    "s5": np.random.randint(1,100, sample)
    
})

df

roll_number student name father name        DOB  s1  s2  s3  s4  s5
0               1          Ali       Iqbal 1983-03-06  99  56  67  85  70
1               2         Raza      Hashim 1997-01-02  64   4   5   5  79
2               3       Junaid        Ebad 1993-05-05  24  38  39  31  15
3               4        Hamza        Ebad 1984-06-06  59  33   3   5  36
4               5          Ali       Yasir 1989-12-13  50  86  80  81  29
...           ...          ...         ...        ...  ..  ..  ..  ..  ..
9995         9996         Raza        Ebad 1990-09-01   8  74  51  88  78
9996         9997         Raza      Hashim 1991-08-19  19  44   3  21  18
9997         9998         Raza      Hashim 1979-07-23  86  33  32  30  82
9998         9999         Raza       Yasir 1979-08-13  69  59  35  26  21
9999        10000        Hamza      Konain 1989-01-09  37  81   1  93  98

[10000 rows x 9 columns]

In [10]:
df.iloc[1:500:2,::]

roll_number student name father name        DOB  s1  s2  s3  s4  s5
1              2         Raza      Hashim 1997-01-02  64   4   5   5  79
3              4        Hamza        Ebad 1984-06-06  59  33   3   5  36
5              6        Hamza       Iqbal 2010-11-21  17  21  71  97  28
7              8         Asif       Yasir 2005-04-08  92   6  71  29  73
9             10         Raza       Yasir 1989-01-03  73  85  23  13  66
..           ...          ...         ...        ...  ..  ..  ..  ..  ..
491          492       Junaid       Iqbal 1975-06-28   1  37  86  93  58
493          494       Junaid       Yasir 1965-02-18  74   8  94  77  13
495          496          Ali       Yasir 1965-03-23  57  96  51   2  25
497          498         Asif      Hashim 2001-12-25  36  10  75   5  64
499          500         Asif      Konain 2001-08-24  43  71   7  69  56

[250 rows x 9 columns]

In [13]:
df.iloc[1:500:,::2]

roll_number father name  s1  s3  s5
1              2      Hashim  64   5  79
3              4        Ebad  59   3  36
5              6       Iqbal  17  71  28
7              8       Yasir  92  71  73
9             10       Yasir  73  23  66
..           ...         ...  ..  ..  ..
491          492       Iqbal   1  86  58
493          494       Yasir  74  94  13
495          496       Yasir  57  51  25
497          498      Hashim  36  75  64
499          500      Konain  43   7  56

[250 rows x 5 columns]

In [14]:
df.loc[::,"s1":"s5"]


s1  s2  s3  s4  s5
0     99  56  67  85  70
1     64   4   5   5  79
2     24  38  39  31  15
3     59  33   3   5  36
4     50  86  80  81  29
...   ..  ..  ..  ..  ..
9995   8  74  51  88  78
9996  19  44   3  21  18
9997  86  33  32  30  82
9998  69  59  35  26  21
9999  37  81   1  93  98

[10000 rows x 5 columns]

In [19]:
display(df.head(1))
df.roll_number

roll_number student name father name        DOB  s1  s2  s3  s4  s5
0            1          Ali       Iqbal 1983-03-06  99  56  67  85  70

0           1
1           2
2           3
3           4
4           5
        ...  
9995     9996
9996     9997
9997     9998
9998     9999
9999    10000
Name: roll_number, Length: 10000, dtype: int32

In [21]:
display(df.head(1))
df["student name"]

roll_number student name father name        DOB  s1  s2  s3  s4  s5
0            1          Ali       Iqbal 1983-03-06  99  56  67  85  70

0          Ali
1         Raza
2       Junaid
3        Hamza
4          Ali
         ...  
9995      Raza
9996      Raza
9997      Raza
9998      Raza
9999     Hamza
Name: student name, Length: 10000, dtype: object

In [22]:
df.obtained = 200

In [26]:
df['total'] = 500
df

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
0               1          Ali       Iqbal 1983-03-06  99  56  67  85  70   
1               2         Raza      Hashim 1997-01-02  64   4   5   5  79   
2               3       Junaid        Ebad 1993-05-05  24  38  39  31  15   
3               4        Hamza        Ebad 1984-06-06  59  33   3   5  36   
4               5          Ali       Yasir 1989-12-13  50  86  80  81  29   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
9995         9996         Raza        Ebad 1990-09-01   8  74  51  88  78   
9996         9997         Raza      Hashim 1991-08-19  19  44   3  21  18   
9997         9998         Raza      Hashim 1979-07-23  86  33  32  30  82   
9998         9999         Raza       Yasir 1979-08-13  69  59  35  26  21   
9999        10000        Hamza      Konain 1989-01-09  37  81   1  93  98   

      total  
0       500  
1       500  
2       500  
3       500  
4       500  
...     ...  
9995    500  
9996    500  
9997    500  
9998    500  
9999    500  

[10000 rows x 10 columns]

In [30]:
df.total= 500
df.head(1)


roll_number student name father name        DOB  s1  s2  s3  s4  s5  total
0            1          Ali       Iqbal 1983-03-06  99  56  67  85  70    500

In [31]:
df["obtained"]= df["s1"] + df["s2"] + df["s3"] + df["s4"] + df["s5"]
df

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
0               1          Ali       Iqbal 1983-03-06  99  56  67  85  70   
1               2         Raza      Hashim 1997-01-02  64   4   5   5  79   
2               3       Junaid        Ebad 1993-05-05  24  38  39  31  15   
3               4        Hamza        Ebad 1984-06-06  59  33   3   5  36   
4               5          Ali       Yasir 1989-12-13  50  86  80  81  29   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
9995         9996         Raza        Ebad 1990-09-01   8  74  51  88  78   
9996         9997         Raza      Hashim 1991-08-19  19  44   3  21  18   
9997         9998         Raza      Hashim 1979-07-23  86  33  32  30  82   
9998         9999         Raza       Yasir 1979-08-13  69  59  35  26  21   
9999        10000        Hamza      Konain 1989-01-09  37  81   1  93  98   

      total  obtained  
0       500       377  
1       500       157  
2       500       147  
3       500       136  
4       500       326  
...     ...       ...  
9995    500       299  
9996    500       105  
9997    500       263  
9998    500       210  
9999    500       310  

[10000 rows x 11 columns]

In [32]:
df['percentage'] = df['obtained'] / df['total'] * 100
df

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
0               1          Ali       Iqbal 1983-03-06  99  56  67  85  70   
1               2         Raza      Hashim 1997-01-02  64   4   5   5  79   
2               3       Junaid        Ebad 1993-05-05  24  38  39  31  15   
3               4        Hamza        Ebad 1984-06-06  59  33   3   5  36   
4               5          Ali       Yasir 1989-12-13  50  86  80  81  29   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
9995         9996         Raza        Ebad 1990-09-01   8  74  51  88  78   
9996         9997         Raza      Hashim 1991-08-19  19  44   3  21  18   
9997         9998         Raza      Hashim 1979-07-23  86  33  32  30  82   
9998         9999         Raza       Yasir 1979-08-13  69  59  35  26  21   
9999        10000        Hamza      Konain 1989-01-09  37  81   1  93  98   

      total  obtained  percentage  
0       500       377        75.4  
1       500       157        31.4  
2       500       147        29.4  
3       500       136        27.2  
4       500       326        65.2  
...     ...       ...         ...  
9995    500       299        59.8  
9996    500       105        21.0  
9997    500       263        52.6  
9998    500       210        42.0  
9999    500       310        62.0  

[10000 rows x 12 columns]

In [36]:
def grade(per):
    grade = None
    
    if per >= 80:
        grade = "A+"
    elif per >= 70:
        grade = "A"
    elif per >= 60:
        grade = "B"
    elif per >= 50:
        grade = "C"
    elif per >= 40:
        grade = "D"
    elif per >= 33:
        grade = "E"
    else:
        grade = "Fail"
        
    return grade

grade(28)


'Fail'

In [37]:
df['grade'] = df.percentage.apply(grade)
df

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
0               1          Ali       Iqbal 1983-03-06  99  56  67  85  70   
1               2         Raza      Hashim 1997-01-02  64   4   5   5  79   
2               3       Junaid        Ebad 1993-05-05  24  38  39  31  15   
3               4        Hamza        Ebad 1984-06-06  59  33   3   5  36   
4               5          Ali       Yasir 1989-12-13  50  86  80  81  29   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
9995         9996         Raza        Ebad 1990-09-01   8  74  51  88  78   
9996         9997         Raza      Hashim 1991-08-19  19  44   3  21  18   
9997         9998         Raza      Hashim 1979-07-23  86  33  32  30  82   
9998         9999         Raza       Yasir 1979-08-13  69  59  35  26  21   
9999        10000        Hamza      Konain 1989-01-09  37  81   1  93  98   

      total  obtained  percentage grade  
0       500       377        75.4     A  
1       500       157        31.4  Fail  
2       500       147        29.4  Fail  
3       500       136        27.2  Fail  
4       500       326        65.2     B  
...     ...       ...         ...   ...  
9995    500       299        59.8     C  
9996    500       105        21.0  Fail  
9997    500       263        52.6     C  
9998    500       210        42.0     D  
9999    500       310        62.0     B  

[10000 rows x 13 columns]

In [39]:
sample = 10000


df1 = pd.DataFrame({
    "roll_number": np.arange(1,sample+1),
    "student name": np.random.choice(["Ali","Hamza","Junaid","Asif","Raza"], sample),
    "father name": np.random.choice(["Ebad","Hashim","Konain","Yasir","Iqbal"], sample),
    "DOB": np.random.choice(pd.date_range("1960-01-01", "2015-12-31", freq="D").values, sample),
    "s1": np.random.randint(1,100, sample),
    "s2": np.random.randint(1,100, sample),
    "s3": np.random.randint(1,100, sample),
    "s4": np.random.randint(1,100, sample),
    "s5": np.random.randint(1,100, sample)
    
})

df1


roll_number student name father name        DOB  s1  s2  s3  s4  s5
0               1         Raza      Konain 1969-11-21  91  35  73  75  10
1               2          Ali      Konain 2011-01-04  42  21  40   3  54
2               3         Raza        Ebad 2004-04-22  23  36  61  23  58
3               4          Ali      Hashim 1979-05-20  71  68  95  69  70
4               5         Asif       Yasir 1982-01-27  94  49  85  68  90
...           ...          ...         ...        ...  ..  ..  ..  ..  ..
9995         9996          Ali        Ebad 1967-04-07  43  31  28  39  89
9996         9997       Junaid      Hashim 2001-08-02  32  53  89  84   5
9997         9998          Ali      Hashim 1969-11-30  74  60  16  88  36
9998         9999        Hamza      Hashim 1990-01-10  20  45  54  68   3
9999        10000         Raza        Ebad 1997-10-23  54  64  97  19  63

[10000 rows x 9 columns]

In [40]:
def grading(sub1,sub2,sub3,sub4,sub5):
    return sub1 + sub2 + sub3 + sub4 + sub5

df1.loc[:, "s1":"s5"].apply(lambda x:grading(*x), axis=1)

0       284
1       160
2       201
3       373
4       386
       ... 
9995    230
9996    263
9997    274
9998    190
9999    297
Length: 10000, dtype: int64

In [41]:
def grading(sub1,sub2,sub3,sub4,sub5):
    obt = sub1 + sub2 + sub3 + sub4 + sub5
    total = 500
    per = obt / total * 100
    
    grade = None
    
    if per >= 80:
        grade = "A+"
    elif per >= 70:
        grade = "A"
    elif per >= 60:
        grade = "B"
    elif per >= 50:
        grade = "C"
    elif per >= 40:
        grade = "D"
    elif per >= 33:
        grade = "E"
    else:
        grade = "Fail"
    return total, obt, per, grade

df1.loc[:, "s1":"s5"].apply(lambda x:grading(*x), axis=1)

0                     (500, 284, 56.8, C)
1                  (500, 160, 32.0, Fail)
2                     (500, 201, 40.2, D)
3                     (500, 373, 74.6, A)
4                     (500, 386, 77.2, A)
                      ...                
9995                  (500, 230, 46.0, D)
9996                  (500, 263, 52.6, C)
9997    (500, 274, 54.800000000000004, C)
9998                  (500, 190, 38.0, E)
9999                  (500, 297, 59.4, C)
Length: 10000, dtype: object

In [42]:
def grading(sub1,sub2,sub3,sub4,sub5):
    obt = sub1 + sub2 + sub3 + sub4 + sub5
    total = 500
    per = obt / total * 100
    
    grade = None
    
    if per >= 80:
        grade = "A+"
    elif per >= 70:
        grade = "A"
    elif per >= 60:
        grade = "B"
    elif per >= 50:
        grade = "C"
    elif per >= 40:
        grade = "D"
    elif per >= 33:
        grade = "E"
    else:
        grade = "Fail"
    return total, obt, per, grade

df1[["total",'obtained','percentage','grade']]= df1.loc[:, "s1":"s5"].apply(lambda x:grading(*x), axis=1, result_type="expand")
df1


roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
0               1         Raza      Konain 1969-11-21  91  35  73  75  10   
1               2          Ali      Konain 2011-01-04  42  21  40   3  54   
2               3         Raza        Ebad 2004-04-22  23  36  61  23  58   
3               4          Ali      Hashim 1979-05-20  71  68  95  69  70   
4               5         Asif       Yasir 1982-01-27  94  49  85  68  90   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
9995         9996          Ali        Ebad 1967-04-07  43  31  28  39  89   
9996         9997       Junaid      Hashim 2001-08-02  32  53  89  84   5   
9997         9998          Ali      Hashim 1969-11-30  74  60  16  88  36   
9998         9999        Hamza      Hashim 1990-01-10  20  45  54  68   3   
9999        10000         Raza        Ebad 1997-10-23  54  64  97  19  63   

      total  obtained  percentage grade  
0       500       284        56.8     C  
1       500       160        32.0  Fail  
2       500       201        40.2     D  
3       500       373        74.6     A  
4       500       386        77.2     A  
...     ...       ...         ...   ...  
9995    500       230        46.0     D  
9996    500       263        52.6     C  
9997    500       274        54.8     C  
9998    500       190        38.0     E  
9999    500       297        59.4     C  

[10000 rows x 13 columns]

In [44]:
data = np.array([8,10,20,4,7,15,14])
data

array([ 8, 10, 20,  4,  7, 15, 14])

In [45]:
display(data)
sum(data)/len(data)

array([ 8, 10, 20,  4,  7, 15, 14])

11.142857142857142

In [46]:
#mean
data = np.array([8,10,20,4,7,15,400])
display(data)
display(sum(data)/len(data))
data.mean()

array([  8,  10,  20,   4,   7,  15, 400])

66.28571428571429

66.28571428571429

In [47]:
#median
data = np.array([8,10,20,4,7,15,400])
display(data)
data = np.sort(data)
display(data)
print("Median: ",10)

array([  8,  10,  20,   4,   7,  15, 400])

array([  4,   7,   8,  10,  15,  20, 400])

Median:  10


In [48]:
#mode
data = np.array([8,10,8,4,7,15,400])
display(data)
data = np.sort(data)
display(data)

array([  8,  10,   8,   4,   7,  15, 400])

array([  4,   7,   8,   8,  10,  15, 400])

In [49]:
display(df.head(1))
display(df.tail(1))


roll_number student name father name        DOB  s1  s2  s3  s4  s5  total  \
0            1          Ali       Iqbal 1983-03-06  99  56  67  85  70    500   

   obtained  percentage grade  
0       377        75.4     A

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
9999        10000        Hamza      Konain 1989-01-09  37  81   1  93  98   

      total  obtained  percentage grade  
9999    500       310        62.0     B

In [50]:
df1['Remarks'] = np.random.choice(["Good","Excellent","Very good","poor",None], sample)
df1

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
0               1         Raza      Konain 1969-11-21  91  35  73  75  10   
1               2          Ali      Konain 2011-01-04  42  21  40   3  54   
2               3         Raza        Ebad 2004-04-22  23  36  61  23  58   
3               4          Ali      Hashim 1979-05-20  71  68  95  69  70   
4               5         Asif       Yasir 1982-01-27  94  49  85  68  90   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
9995         9996          Ali        Ebad 1967-04-07  43  31  28  39  89   
9996         9997       Junaid      Hashim 2001-08-02  32  53  89  84   5   
9997         9998          Ali      Hashim 1969-11-30  74  60  16  88  36   
9998         9999        Hamza      Hashim 1990-01-10  20  45  54  68   3   
9999        10000         Raza        Ebad 1997-10-23  54  64  97  19  63   

      total  obtained  percentage grade    Remarks  
0       500       284        56.8     C  Excellent  
1       500       160        32.0  Fail       poor  
2       500       201        40.2     D       Good  
3       500       373        74.6     A  Excellent  
4       500       386        77.2     A       poor  
...     ...       ...         ...   ...        ...  
9995    500       230        46.0     D  Excellent  
9996    500       263        52.6     C       poor  
9997    500       274        54.8     C       None  
9998    500       190        38.0     E  Very good  
9999    500       297        59.4     C       poor  

[10000 rows x 14 columns]

In [51]:
df1.notnull().sum()

roll_number     10000
student name    10000
father name     10000
DOB             10000
s1              10000
s2              10000
s3              10000
s4              10000
s5              10000
total           10000
obtained        10000
percentage      10000
grade           10000
Remarks          7963
dtype: int64

In [52]:
df1.notnull().sum()/len(df1)*100

roll_number     100.00
student name    100.00
father name     100.00
DOB             100.00
s1              100.00
s2              100.00
s3              100.00
s4              100.00
s5              100.00
total           100.00
obtained        100.00
percentage      100.00
grade           100.00
Remarks          79.63
dtype: float64

In [53]:
df1.notnull().sum(axis=1)

0       14
1       14
2       14
3       14
4       14
        ..
9995    14
9996    14
9997    13
9998    14
9999    14
Length: 10000, dtype: int64

In [54]:
df1['cell'] = df1.notnull().sum(axis=1)
df1

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
0               1         Raza      Konain 1969-11-21  91  35  73  75  10   
1               2          Ali      Konain 2011-01-04  42  21  40   3  54   
2               3         Raza        Ebad 2004-04-22  23  36  61  23  58   
3               4          Ali      Hashim 1979-05-20  71  68  95  69  70   
4               5         Asif       Yasir 1982-01-27  94  49  85  68  90   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
9995         9996          Ali        Ebad 1967-04-07  43  31  28  39  89   
9996         9997       Junaid      Hashim 2001-08-02  32  53  89  84   5   
9997         9998          Ali      Hashim 1969-11-30  74  60  16  88  36   
9998         9999        Hamza      Hashim 1990-01-10  20  45  54  68   3   
9999        10000         Raza        Ebad 1997-10-23  54  64  97  19  63   

      total  obtained  percentage grade    Remarks  cell  
0       500       284        56.8     C  Excellent    14  
1       500       160        32.0  Fail       poor    14  
2       500       201        40.2     D       Good    14  
3       500       373        74.6     A  Excellent    14  
4       500       386        77.2     A       poor    14  
...     ...       ...         ...   ...        ...   ...  
9995    500       230        46.0     D  Excellent    14  
9996    500       263        52.6     C       poor    14  
9997    500       274        54.8     C       None    13  
9998    500       190        38.0     E  Very good    14  
9999    500       297        59.4     C       poor    14  

[10000 rows x 15 columns]

In [55]:
df1.sort_values("cell")

roll_number student name father name        DOB  s1  s2  s3  s4  s5  \
4999         5000         Asif      Konain 2000-03-30  37  48  36  15   5   
8424         8425          Ali        Ebad 1979-12-11  54  29  69  18  84   
8423         8424       Junaid       Iqbal 1996-12-14   1  21  31  54  46   
1980         1981         Raza      Hashim 2013-05-21  95   3  51  37  43   
1981         1982        Hamza        Ebad 1974-05-22  41  80  39  26   2   
...           ...          ...         ...        ...  ..  ..  ..  ..  ..   
3719         3720         Raza        Ebad 1968-01-09  16  79  35  95  23   
3720         3721       Junaid        Ebad 2006-04-30  57   4  59  27  88   
3721         3722         Raza      Hashim 2001-11-10  14  97   3  91  94   
3715         3716        Hamza       Iqbal 2008-08-14  24   2   2  10  30   
9999        10000         Raza        Ebad 1997-10-23  54  64  97  19  63   

      total  obtained  percentage grade    Remarks  cell  
4999    500       141        28.2  Fail       None    13  
8424    500       254        50.8     C       None    13  
8423    500       153        30.6  Fail       None    13  
1980    500       229        45.8     D       None    13  
1981    500       188        37.6     E       None    13  
...     ...       ...         ...   ...        ...   ...  
3719    500       248        49.6     D  Very good    14  
3720    500       235        47.0     D       poor    14  
3721    500       299        59.8     C       Good    14  
3715    500        68        13.6  Fail  Very good    14  
9999    500       297        59.4     C       poor    14  

[10000 rows x 15 columns]

In [56]:
df1.grade.unique()


array(['C', 'Fail', 'D', 'A', 'B', 'E', 'A+'], dtype=object)

In [57]:
df1.grade.value_counts()

D       2783
C       2778
B       1623
E       1294
Fail     933
A        520
A+        69
Name: grade, dtype: int64

In [58]:
df1.grade.value_counts(normalize=True)

D       0.2783
C       0.2778
B       0.1623
E       0.1294
Fail    0.0933
A       0.0520
A+      0.0069
Name: grade, dtype: float64

In [59]:
df1.grade.value_counts(normalize=True)*100

D       27.83
C       27.78
B       16.23
E       12.94
Fail     9.33
A        5.20
A+       0.69
Name: grade, dtype: float64